const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style=`
 *{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;background:#242424;color:#f3f4f6;font:15px/1.5 'Microsoft YaHei',system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:0 24px 24px}
 .admin-header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:16px 20px;background:#080808;border:1px solid #484848;border-top:0;border-radius:0 0 8px 8px}
 h1{margin:0;color:#9ca3af;font-size:24px;font-weight:400}h1 small{margin-left:12px;font-size:14px;color:#7c3aed}h2{margin:0 0 20px;font-size:20px;font-weight:400;color:#9ca3af}
 .admin-header-actions{display:flex;align-items:center;gap:12px}.admin-current{color:#9ca3af;font-size:14px}.admin-card{padding:20px;border:1px solid #484848;border-radius:8px;background:#242424}
 .admin-auth{max-width:520px;margin:8vh auto}.admin-layout{display:grid;grid-template-columns:340px minmax(0,1fr);gap:20px;margin-top:20px;align-items:start}.admin-data{margin-top:20px}
 .admin-field{margin-bottom:16px}label{display:block;margin-bottom:6px;color:#9ca3af;font-size:14px}input,select{display:block;width:100%;height:38px;padding:7px 12px;border:1px solid #484848;border-radius:8px;background:#242424;color:#f3f4f6;font:inherit;color-scheme:dark;min-width:0}
 input:focus,select:focus{outline:2px solid #7c3aed;outline-offset:1px}input[readonly],select:disabled{color:#9ca3af}input::placeholder{color:#737a87}button{font:inherit;cursor:pointer}
 .admin-button{display:inline-flex;align-items:center;justify-content:center;min-height:34px;padding:6px 14px;border:1px solid #484848;border-radius:8px;background:#242424;color:#9ca3af;font:14px/1.5 'Microsoft YaHei',system-ui,sans-serif;white-space:nowrap}
 .admin-button:hover{border-color:#7c3aed;color:#fff}.admin-primary{background:#7c3aed;border-color:#7c3aed;color:#fff}.admin-primary:hover{background:#6d28d9}.admin-danger{border-color:#704040;color:#fca5a5}.admin-danger:hover{border-color:#ef4444;color:#fecaca}.admin-button:focus-visible{outline:2px solid #a78bfa;outline-offset:3px}.admin-button:disabled{opacity:.45;cursor:not-allowed}
 .admin-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:24px}.admin-full{width:100%}.admin-note{color:#9ca3af;font-size:14px;line-height:1.7;margin:0 0 16px;overflow-wrap:anywhere}.admin-note p{margin:0 0 6px}
 .admin-notice{margin:20px 0 0;padding:10px 14px;border:1px solid #484848;border-radius:8px;color:#10b981;overflow-wrap:anywhere}.admin-notice.error{color:#fca5a5;border-color:#704040}.admin-notice[hidden]{display:none}
 .admin-table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:14px}.admin-table th,.admin-table td{padding:12px 8px;border-bottom:1px solid #484848;text-align:left;overflow-wrap:anywhere;vertical-align:middle}.admin-table th{color:#9ca3af;font-weight:400}.admin-table th:first-child{width:38%}.admin-table th:last-child{width:76px}.admin-table tr:last-child td{border-bottom:0}.admin-role{color:#a78bfa}.admin-inactive{color:#f87171}
 .admin-counts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:16px}.admin-count{border:1px solid #484848;border-radius:8px;padding:12px}.admin-count span{display:block;color:#9ca3af;font-size:14px}.admin-count strong{display:block;margin-top:4px;font-size:24px;font-weight:500}
 details{margin-bottom:20px;border-top:1px solid #484848;padding-top:16px}summary{cursor:pointer;color:#9ca3af;margin-bottom:16px}dialog{width:460px;max-width:calc(100vw - 32px);padding:24px;color:#f3f4f6;background:#242424;border:1px solid #484848;border-radius:10px}dialog::backdrop{background:rgba(0,0,0,.6)}dialog h2{margin-bottom:12px}dialog .admin-actions{justify-content:flex-end}
 @media(max-width:767px){main{padding:0 12px 16px}.admin-header{padding:14px 12px}.admin-header-actions{gap:8px}.admin-current{display:none}h1{font-size:20px}.admin-layout{grid-template-columns:minmax(0,1fr)}.admin-card{padding:16px}.admin-auth{margin-top:32px}.admin-table th,.admin-table td{padding:10px 4px}.admin-count{padding:10px 8px}.admin-counts{gap:8px}}
`;
const passwordFields=(prefix,required=true)=>`<div class="admin-field"><label for="${prefix}Password">${prefix==='account'?'密码':'管理员密码'}</label><input id="${prefix}Password" name="password" type="password" autocomplete="new-password" minlength="6" maxlength="200" placeholder="6至200个字符"${required?' required':''}></div><div class="admin-field"><label for="${prefix}Confirm">确认密码</label><input id="${prefix}Confirm" name="confirm_password" type="password" autocomplete="new-password" minlength="6" maxlength="200"${required?' required':''}></div>`;
const notice=error=>`<p id="adminNotice" class="admin-notice${error?' error':''}" role="status" aria-live="polite"${error?'':' hidden'}>${escapeHTML(error)}</p>`;

export function adminPage({mode='login',user,error='',setupKeyRequired=false,setupAllowed=true}={}) {
 let content;
 if(mode==='manage') {
  content=`<header class="admin-header"><h1>用户设置<small>admin</small></h1><div class="admin-header-actions"><span class="admin-current">${escapeHTML(user.username)}</span><button class="admin-button" id="adminLogout" type="button">退出管理</button></div></header>${notice(error)}<div class="admin-layout"><section class="admin-card"><h2 id="accountTitle">新增用户</h2><form id="accountForm" method="POST" action="/admin/users"><div class="admin-field"><label for="accountUsername">用户名</label><input id="accountUsername" name="username" required maxlength="80" autocomplete="off"></div>${passwordFields('account')}<div class="admin-field"><label for="accountRole">用户角色</label><select id="accountRole" name="role"><option value="user">普通用户</option><option value="admin">管理员</option></select></div><div class="admin-field" id="accountStateField" hidden><label for="accountState">账户状态</label><select id="accountState" name="is_active"><option value="1">启用</option><option value="0">停用</option></select></div><div class="admin-note"><p>管理员：可删除业务、导出 PDF 和管理用户。</p><p>普通用户：可查看、新增、编辑业务，不能删除业务或导出 PDF。</p></div><div class="admin-actions"><button class="admin-button" id="accountCancel" type="button" hidden>取消编辑</button><button class="admin-button admin-primary" id="accountSave" type="submit">创建用户</button></div></form></section><section class="admin-card"><h2>账户列表</h2><table class="admin-table"><thead><tr><th>用户名</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody id="adminUsers"></tbody></table><p class="admin-note" style="margin:16px 0 0">修改角色、停用账户或重设密码后，该账户需要重新登录。</p></section></div><section class="admin-card admin-data"><h2>测试数据</h2><div class="admin-counts"><div class="admin-count"><span>业务总数</span><strong id="adminTotal">—</strong></div><div class="admin-count"><span>正式业务</span><strong id="adminFormal">—</strong></div><div class="admin-count"><span>测试业务</span><strong id="adminTest">—</strong></div></div><p class="admin-note">每次导入200条近12周有明显起伏、总体上升的测试业务，报名早于投标，已报名或已投标业务均已获取标书。通过本页导入的测试业务按来源标记，即使编辑过也会清除；手动录入的正式业务及现有未标记业务保留。</p><div class="admin-actions"><button class="admin-button admin-primary" id="adminImport" type="button">导入200条测试数据</button><button class="admin-button admin-danger" id="adminClear" type="button" disabled>清除测试数据</button></div></section><dialog id="adminClearDialog" aria-labelledby="clearTitle"><h2 id="clearTitle">清除测试数据</h2><p id="adminClearMessage" class="admin-note"></p><div class="admin-actions"><button class="admin-button" id="adminClearCancel" type="button">放弃</button><button class="admin-button admin-danger" id="adminClearExecute" type="button">执行</button></div></dialog>`;
 } else if(mode==='setup') {
  content=`<section class="admin-card admin-auth"><h1 style="margin-bottom:24px">初始用户设置<small>admin</small></h1><p class="admin-note">设置首个管理员账户，也可以同时创建一个普通用户。</p>${notice(error)}${setupAllowed?`<form id="setupForm" method="POST" action="/admin/setup">${setupKeyRequired?'<div class="admin-field"><label for="setupKey">初始化密钥</label><input id="setupKey" name="setup_key" type="password" autocomplete="off" required></div>':''}<div class="admin-field"><label for="setupUsername">管理员用户名</label><input id="setupUsername" name="username" value="admin" maxlength="80" autocomplete="username" required></div>${passwordFields('setup')}<details><summary>同时创建普通用户（可选）</summary><div class="admin-field"><label for="ordinaryUsername">普通用户用户名</label><input id="ordinaryUsername" maxlength="80" autocomplete="off"></div><div class="admin-field"><label for="ordinaryPassword">普通用户密码</label><input id="ordinaryPassword" type="password" minlength="6" maxlength="200" autocomplete="new-password" placeholder="6至200个字符"></div><div class="admin-field"><label for="ordinaryConfirm">确认普通用户密码</label><input id="ordinaryConfirm" type="password" minlength="6" maxlength="200" autocomplete="new-password"></div></details><div class="admin-actions"><button class="admin-button admin-primary admin-full" type="submit">完成初始设置</button></div></form>`:'<p class="admin-notice error">请部署者先配置初始化密钥，再刷新本页。</p>'}</section>`;
 } else {
  content=`<section class="admin-card admin-auth"><h1 style="margin-bottom:24px">用户设置<small>admin</small></h1><p class="admin-note">请使用管理员账户登录。</p>${notice(error)}<form id="adminLoginForm" method="POST" action="/admin/login"><div class="admin-field"><label for="adminUsername">用户名</label><input id="adminUsername" name="username" maxlength="80" autocomplete="username" required></div><div class="admin-field"><label for="adminPassword">密码</label><input id="adminPassword" name="password" type="password" maxlength="200" autocomplete="current-password" required></div><div class="admin-actions"><button class="admin-button admin-primary admin-full" type="submit">登录用户设置</button></div></form></section>`;
 }
 return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>admin · 用户设置 · BidManager</title><style>${style}</style></head><body><main>${content}<noscript><p class="admin-notice error">请启用JavaScript后使用用户设置。</p></noscript></main><script>
const mode=${JSON.stringify(mode)},currentId=${Number(user?.id)||0};
const notice=document.getElementById('adminNotice');
function showNotice(message,error=false){notice.textContent=message;notice.hidden=!message;notice.classList.toggle('error',error);}
async function proof(password,salt,iterations=310000){const encoder=new TextEncoder(),key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);const result=await crypto.subtle.deriveBits({name:'PBKDF2',salt:encoder.encode(salt),iterations,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(result),x=>x.toString(16).padStart(2,'0')).join('');}
async function credential(password,confirm){if(password.length<6||password.length>200)throw new Error('密码需要6至200个字符');if(password!==confirm)throw new Error('两次输入的密码不一致');const salt=Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('');return {salt,proof:await proof(password,salt)};}
async function request(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.message||'操作失败');return data;}
async function busy(button,run){button.disabled=true;try{await run();}catch(error){showNotice(error.message||'操作失败',true);}finally{button.disabled=false;}}
const setupForm=document.getElementById('setupForm');
if(setupForm)setupForm.addEventListener('submit',async event=>{event.preventDefault();await busy(setupForm.querySelector('button[type=submit]'),async()=>{const body={username:document.getElementById('setupUsername').value.trim(),credential:await credential(document.getElementById('setupPassword').value,document.getElementById('setupConfirm').value),setup_key:document.getElementById('setupKey')?.value||''};const username=document.getElementById('ordinaryUsername').value.trim(),password=document.getElementById('ordinaryPassword').value,confirm=document.getElementById('ordinaryConfirm').value;if(username||password||confirm){if(!username)throw new Error('请填写普通用户用户名');body.ordinary={username,credential:await credential(password,confirm)};}await request('/admin/setup',body);location.assign('/admin');});});
const loginForm=document.getElementById('adminLoginForm');
if(loginForm)loginForm.addEventListener('submit',async event=>{event.preventDefault();await busy(loginForm.querySelector('button'),async()=>{const username=document.getElementById('adminUsername').value.trim(),password=document.getElementById('adminPassword').value;const challenge=await request('/api/auth/challenge?username='+encodeURIComponent(username));const form=new FormData();form.set('username',username);form.set('proof',await proof(password,challenge.salt,challenge.iterations));const response=await fetch('/admin/login',{method:'POST',body:form});if(response.redirected){location.assign('/admin');return;}const doc=new DOMParser().parseFromString(await response.text(),'text/html');throw new Error(doc.getElementById('adminNotice')?.textContent||'登录失败');});});
if(mode==='manage'){
 let users=[],editingId=null,testCount=0;
 const form=document.getElementById('accountForm'),save=document.getElementById('accountSave'),cancel=document.getElementById('accountCancel'),role=document.getElementById('accountRole'),state=document.getElementById('accountState'),password=document.getElementById('accountPassword'),confirm=document.getElementById('accountConfirm'),username=document.getElementById('accountUsername');
 function resetForm(){editingId=null;form.reset();username.readOnly=false;role.disabled=false;state.disabled=false;password.required=true;confirm.required=true;password.placeholder='6至200个字符';document.getElementById('accountTitle').textContent='新增用户';save.textContent='创建用户';cancel.hidden=true;document.getElementById('accountStateField').hidden=true;}
 function editUser(id){const user=users.find(user=>user.id===id);if(!user)return;editingId=id;username.value=user.username;username.readOnly=true;role.value=user.role;state.value=String(user.is_active);role.disabled=id===currentId;state.disabled=id===currentId;password.value='';confirm.value='';password.required=false;confirm.required=false;password.placeholder='留空则保留原密码';document.getElementById('accountTitle').textContent='编辑用户';save.textContent='保存设置';cancel.hidden=false;document.getElementById('accountStateField').hidden=false;form.scrollIntoView({block:'nearest',behavior:'smooth'});}
 async function refresh(){const data=await request('/admin/users');users=data.users;testCount=data.data.test;document.getElementById('adminTotal').textContent=data.data.total;document.getElementById('adminFormal').textContent=data.data.manual;document.getElementById('adminTest').textContent=testCount;document.getElementById('adminClear').disabled=!testCount;const tbody=document.getElementById('adminUsers');tbody.replaceChildren();for(const user of users){const row=document.createElement('tr');row.dataset.id=user.id;for(const value of [user.username+(user.id===currentId?'（当前）':''),user.role==='admin'?'管理员':'普通用户',user.is_active?'启用':'停用']){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}if(user.role==='admin')row.children[1].className='admin-role';if(!user.is_active)row.children[2].className='admin-inactive';const cell=document.createElement('td'),button=document.createElement('button');button.type='button';button.className='admin-button';button.textContent='编辑';button.addEventListener('click',()=>editUser(user.id));cell.append(button);row.append(cell);tbody.append(row);}}
 cancel.addEventListener('click',resetForm);
 form.addEventListener('submit',async event=>{event.preventDefault();await busy(save,async()=>{const body={username:username.value.trim(),role:role.value,is_active:Number(state.value)};if(password.value||confirm.value||!editingId)body.credential=await credential(password.value,confirm.value);const data=await request(editingId?'/admin/users/'+editingId:'/admin/users',body);showNotice(data.message);if(data.reauth){location.assign('/admin');return;}resetForm();await refresh();});});
 document.getElementById('adminLogout').addEventListener('click',event=>busy(event.currentTarget,async()=>{await request('/admin/logout',{});location.assign('/admin');}));
 document.getElementById('adminImport').addEventListener('click',event=>busy(event.currentTarget,async()=>{const data=await request('/admin/test-data/import',{});showNotice(data.message);await refresh();}));
 const dialog=document.getElementById('adminClearDialog');
 document.getElementById('adminClear').addEventListener('click',()=>{document.getElementById('adminClearMessage').textContent='将清除全部'+testCount+'条自动导入的测试业务，包括修改过的测试业务。手动录入的正式业务会保留。';dialog.showModal();});
 document.getElementById('adminClearCancel').addEventListener('click',()=>dialog.close());
 document.getElementById('adminClearExecute').addEventListener('click',event=>busy(event.currentTarget,async()=>{const data=await request('/admin/test-data/clear',{confirm:true});dialog.close();showNotice(data.message);await refresh();}));
 refresh().catch(error=>showNotice(error.message,true));
}
</script></body></html>`;
}
